### ISSUE TITLE
LaTeX Equation Formatted Incorrectly

### ISSUE THREAD

**Issue by alphawent** [cristianvasquez/obsidian-prettify#21] opened 2020-12-19 08:06 UTC
It seems that LaTeX formulas with multiple lines will be formatted incorrectly  
P.S. Markdown Prettifier version 0.0.4  
e.g.

```markdown
$$
\gamma
=
\alpha
+ \beta
$$
```
will be transformed into
```markdown
# $$
\gamma

\alpha

*   \beta

$$
```

**Comment by cristianvasquez** [comment] 2020-12-19 10:21
Hello @alphawent , I cannot reproduce this.

Are you using v.0.0.4 ?

**Comment by cristianvasquez** [comment] 2020-12-21 13:32
I think this was fixed in he last version

**Closed as completed by cristianvasquez** 2020-12-21 13:32 UTC
